### ISSUE TITLE
what kind of message should I send to the vehicle (model3) to open the driver's door? 

### ISSUE THREAD

**Issue by zhy2020** [kaedenbrinkman/PyTeslaBLE#4] opened 2023-05-13 15:07 UTC
Hello, what kind of message should I send to the vehicle (model3) to open the driver's door? Just like the app function of the Tesla App. I tried to send a ClosureMoveRequest message, but the vehicle did not respond.
![c36466a3b1bc092c901f77ed30267ac](https://github.com/kaedenbrinkman/PyTeslaBLE/assets/61862986/6135d523-45ff-4690-94e1-54d856a9dfab)

**Comment by kaedenbrinkman** [comment] 2023-05-13 17:52
`ClosureMoveRequest` is the correct message. What does your code look like?

I haven't tested this, but something like this should work:
```python
def openDriverDoorMsg(self):
    # opens the driver door
    msg = VCSEC_pb2.UnsignedMessage()
    msg.ClosureMoveRequest = VCSEC_pb2.ClosureMoveRequest()
    msg.ClosureMoveRequest.frontDriverDoor = VCSEC_pb2.ClosureMoveType_E.CLOSURE_MOVE_TYPE_OPEN
    return self.signedToMsg(msg)
```

Note: Edited to correct based on [docs](https://teslabtapi.lexnastin.com/docs/more/closures).

**Comment by zhy2020** [comment] 2023-05-20 14:51
> ```python
> ClosureMoveRequest
> ```

I verified that the ClosureMoveRequest was correct, but I sent the wrong data length

**Comment by LexNastin** [comment] 2023-05-23 10:30
So I'm assuming the issue is resolved, so I'll close it. If it isn't, feel free to reopen.

**Closed as completed by LexNastin** 2023-05-23 10:30 UTC
