### ISSUE TITLE
Responding to authentication request during whitelist event

### ISSUE THREAD

**Issue by Lythinari** [kaedenbrinkman/PyTeslaBLE#2] opened 2022-05-24 11:13 UTC
First off, thanks for the python library - ArchGryphon pointed me to your repo.

It looks like the `handle_notify` callback is handling the authentication request before a shared key has been created. 

Car software version: 2022.12.3.3

Here's a capture of the output logs from the car, after the `wait` event comes through the `authenticationRequest` comes through and code exits because the ephemeral key doesnt exist.

With a bit of playing around, I think at the whitelist & ephemeral stage the `authenticationRequest` can be ignored until the shared key is created.

```
Connecting to: <CAR>
Successfully connected, listing services...
2022-05-15 14:13:16.265 Python[7099:647112] Updated notification state for characteristic: 00000213-B2D1-43F0-9B88-960CEBF8B91E
2022-05-15 14:13:17.285 Python[7099:647005] Characteristic 00000212-B2D1-43F0-9B88-960CEBF8B91E could not be written
Message from notification:
commandStatus {
  operationStatus: OPERATIONSTATUS_WAIT
  signedMessageStatus {
  }
}

Looping
Message from notification:
authenticationRequest {
  requestedLevel: AUTHENTICATION_LEVEL_DRIVE
}

Message from notification:
authenticationRequest {
  requestedLevel: AUTHENTICATION_LEVEL_DRIVE
}
.....
```

**Comment by LexNastin** [comment] 2022-05-24 13:55
Ye, that's a problem, I'm not fully sure if we ever even check whether we're whitelisted with the car, will check it out later today if I remember.

**Comment by LexNastin** [comment] 2022-05-29 14:24
Fixed in 0ee3d11, close the issue if the problem is fixed please.

**Comment by LexNastin** [comment] 2022-05-29 14:48
Fixed it in the wrong place, fixed that in commit ceba982.

**Comment by kaedenbrinkman** [comment] 2022-08-28 02:02
@ArchGryphon9362, thanks so much for the quick response. I've pushed your changes to PyPi.
@Lythinari, let me know if this is still an issue.

**Closed as completed by kaedenbrinkman** 2022-08-28 02:02 UTC
Labels: bug

**Comment by kaedenbrinkman** [comment] 2022-09-20 03:23
FYI, reversed the changes in `handle_notify` as this prevents the device from being able to receive the shared key from the vehicle.
